//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtodor_56_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetails
    {
        public int PurchaseDetailID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Purchases Purchases { get; set; }
    }
}
